scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['hello_world:9091']

  - job_name: 'blackbox'
    metrics_path: /probe
    scrape_interval: 5s
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://hello_world:5000/healthcheck
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
